import { Routes } from '@angular/router';
import { HomeComponent } from './pages/sidebar/home/home.component';
import { HistoryComponent } from './pages/sidebar/history/history.component';
import { AboutComponent } from './pages/sidebar/about/about.component';
import { PopularComponent } from './pages/sidebar/popular/popular.component';
import { CategoriesComponent } from './pages/sidebar/categories/categories.component';
import { LoginComponent } from './pages/auth/login/login.component';
import { RegisterComponent } from './pages/auth/register/register.component';
import { ForgotPasswordComponent } from './pages/auth/forgot-password/forgot-password.component';
import { ProfileComponent } from './pages/profile/profile.component';
import { TopicComponent } from './pages/topic/topic.component';
import { ThreadPageComponent } from './pages/thread-page/thread-page.component';
import { NotFoundComponent } from './pages/not-found/not-found.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'about', component: AboutComponent },
  { path: 'history', component: HistoryComponent },
  { path: 'popular', component: PopularComponent },
  { path: 'categories', component: CategoriesComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'topic/:slug', component: TopicComponent },
  { path: 'thread/:id', component: ThreadPageComponent },
  { path: 'profile/:username', component: ProfileComponent },
  { path: 'not-found', component: NotFoundComponent },
  { path: '**', redirectTo: 'not-found' },
];
